//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THITHUWEB.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class LOAITAISAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOAITAISAN()
        {
            this.TAISANs = new HashSet<TAISAN>();
        }
        
        public string MaLTS { get; set; }
       
        public string TenLTS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAISAN> TAISANs { get; set; }
    }
}
