//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THITHUWEB.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Thi61CNTT_61134311Entities : DbContext
    {
        public Thi61CNTT_61134311Entities()
            : base("name=Thi61CNTT_61134311Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LOAITAISAN> LOAITAISANs { get; set; }
        public virtual DbSet<TAISAN> TAISANs { get; set; }
    
        public virtual int TaiSan_TimKiem(string tenTS, string giaMin, string giaMax)
        {
            var tenTSParameter = tenTS != null ?
                new ObjectParameter("TenTS", tenTS) :
                new ObjectParameter("TenTS", typeof(string));
    
            var giaMinParameter = giaMin != null ?
                new ObjectParameter("giaMin", giaMin) :
                new ObjectParameter("giaMin", typeof(string));
    
            var giaMaxParameter = giaMax != null ?
                new ObjectParameter("giaMax", giaMax) :
                new ObjectParameter("giaMax", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TaiSan_TimKiem", tenTSParameter, giaMinParameter, giaMaxParameter);
        }
    }
}
