//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THITHUWEB.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class TAISAN
    {
        [DisplayName("Mã tài sản")]
        public string MaTS { get; set; }
        [DisplayName("Tên tài sản")]
        public string TenTS { get; set; }
        [DisplayName("Đơn vị tính")]
        public string DVT { get; set; }
        [DisplayName("Xuất sứ")]
        public Nullable<bool> XuatSu { get; set; }
        [DisplayName("Đơn giá")]
        public Nullable<int> DonGia { get; set; }
        [DisplayName("Ảnh minh hoạ")]
        public string AnhMH { get; set; }
        [DisplayName("Mã loại tài sản")]
        public string MaLTS { get; set; }
        [DisplayName("Ghi chú")]
        public string GhiChu { get; set; }
    
        public virtual LOAITAISAN LOAITAISAN { get; set; }
    }
}
